### ISSUE TITLE
zktools.locking.ZkLock doesn't use a guid in ephemeral nodes

### ISSUE THREAD

**Issue by jimfulton** [mozilla-services/zktools#2]
I just read the lock recipe:

  http://zookeeper.apache.org/doc/trunk/recipes.html#sc_recipes_Locks

It describes including a guid in ephemeral node names so a client can determine the node name if the server fails after creating the ephemeral node but before returning it's name to the client.

zktools 0.2.1 doesn't do this.

**Comment by bbangert** [comment]
Ah, this is new in the recipe, I hadn't seen it originally. zktools will be updated to handle it.

**Comment by bbangert** [comment]
It does now! :)
